# Exported from Render on 2025-03-18T20:17:56Z
databases:
  databaseName: connectteck
  user: ucmerced
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"

services:
  - type: web
    name: backend-service
    runtime: node
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Backend  # ✅ Use the existing database
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
