services:
  - type: web
    name: backend-service
    runtime: node
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Backend  # ✅ Use the existing database
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
