# Exported from Render on 2025-03-18T20:17:56Z
databases:
- name: Backend
  databaseName: connectteck
  user: ucmerced
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "17"
version: "1"
