/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/createAccount` | `/createAccount`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SidebarContent` | `/SidebarContent`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TagModal` | `/TagModal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ThemeContext` | `/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/createAccount` | `/createAccount`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SidebarContent` | `/SidebarContent`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/TagModal` | `/TagModal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ThemeContext` | `/ThemeContext`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/createAccount${`?${string}` | `#${string}` | ''}` | `/createAccount${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SidebarContent${`?${string}` | `#${string}` | ''}` | `/SidebarContent${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/TagModal${`?${string}` | `#${string}` | ''}` | `/TagModal${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ThemeContext${`?${string}` | `#${string}` | ''}` | `/ThemeContext${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/createAccount` | `/createAccount`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SidebarContent` | `/SidebarContent`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TagModal` | `/TagModal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ThemeContext` | `/ThemeContext`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
